[build]
  publish = "."
  command = "cd 'Awesome Websites/Bulk File Renamer' && npm ci && npm run build && cd '../Gitmoji-Helper' && pnpm i && pnpm run build"

[build.environment]
  NODE_VERSION = "24"